# Generated by Django 3.1.14 on 2025-03-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя покемона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pokemons', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Имя на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Имя на японском')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='Предыдущая эволюция')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Появление')),
                ('disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Исчезновение')),
                ('level', models.PositiveIntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('health', models.PositiveIntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('strength', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сила')),
                ('defence', models.PositiveIntegerField(blank=True, null=True, verbose_name='Защита')),
                ('stamina', models.PositiveIntegerField(blank=True, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
